travis:
  secure:
    BINSTAR_TOKEN: Z150GoINJpBsHkJT8t8DNHY3lLX3i+MlZ8szYAJoV7r7aAwko8detFIv+NDPdPjEhI7KgDku0cO6nrluTT+pkMRq019E5bAhfGIwZnGlJsbo3FsgXl44oSbILff8LQg52xg+S2HWnepCROA5bhbiRODQ+3XaEKLxeFiIIZRym8RMXzCGpecgCsvCwdXki9pbab4NbmzdQ0JIsXHaxGgwzsldIn2g7zae98NxjVzZpblfJ9LeQbtjEmxlyJ59qXs3DrJ+kaXPE+R0fmSJytf+pQyz1vMR7Okh+ldKDgBq20dNh13DLooU/derBvbf7jymUIBnOMLFBLhECRgMx/c0bSunKyCBb3uO/vqZQf3TIQxVtues5agN3RU2dWjbUCJil5oXilkR/jKwqa3M1jrw6E1TvLrOfEv4gLtvAeh7lg2OlLdwswwHZohvS41IYDmVTF9kty2C/Z65qAcuLICaqYIyWRKX9awy2p8SMso6G7z+dpRDt4ZVG4sQCLUDH1l4BwRsLf5G8YkUWp9XY4vYndeTLm/mR5G5bcxSZ7ebgAug0y4yAp9Av8LTnKWKmRQPyARaHloH0P5G94tbWoByBglB3fyE/a1vlo8Rt3/XoS52cyWrEJlfjdFLpQKQgvgZMQ1eBBcsVlkPC9y9aKBueA9rE34s7D0iUT2il5wSGtA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
